AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateCluster: !Equals
    - ''
    - !Ref 'ParameterClusterName'
  CreateLoadBalancer: !Equals
    - ''
    - !Ref 'ParameterLoadBalancerARN'
Description: CloudFormation template to deploy Orthanc on AWS
Parameters:
  ParameterClusterName:
    Description: Name of the ECS cluster to deploy to (optional)
    Type: String
  ParameterLoadBalancerARN:
    Description: Name of the LoadBalancer to connect to (optional)
    Type: String
  ConainerImageUrl:
    Description: The url of a docker image that contains the application process that will handle the traffic for this service
    Default: flamingofugang/nginx-orthanc-plugins:latest
    Type: String
  PublicSubnet1Id:
    Description: PublicSubnetId, for Availability Zone 1 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2Id:
    Description: PublicSubnetId, for Availability Zone 2 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1Id:
    Description: PrivateSubnetId, for Availability Zone 1 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2Id:
    Description: PrivateSubnetId, for Availability Zone 2 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  ParameterVPCId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m3.xlarge
    AllowedValues: [t2.large, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
  RDSDBInstanceClass:
    Type: String
    Default: "db.t3.medium"
  RDSDBStorageType:
    Type: String
    Default: "gp2"
  RDSDBAllocatedStorage:
    Type: Number
    Default: 20

Mappings:
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-0c1f575380708aa63
    us-east-2:
      AMIID: ami-015a2afe7e1a8af56
    us-west-1:
      AMIID: ami-032a827d612b78a50
    us-west-2:
      AMIID: ami-05edb14e89a5b98f3
    ap-northeast-1:
      AMIID: ami-06ee72c3360fd7fad
    ap-northeast-2:
      AMIID: ami-0cfc5eb79eceeeec9
    ap-south-1:
      AMIID: ami-078902ae8103daac8
    ap-southeast-1:
      AMIID: ami-09dd721a797640468
    ap-southeast-2:
      AMIID: ami-040bd2e2325535b3d
    ca-central-1:
      AMIID: ami-0a06b44c462364156
    eu-central-1:
      AMIID: ami-09509e8f8dea8ab83
    eu-north-1:
      AMIID: ami-015b157d082fd4e0d
    eu-west-1:
      AMIID: ami-0489c3efb4fe85f5d
    eu-west-2:
      AMIID: ami-037dd70536680c11f
    eu-west-3:
      AMIID: ami-0182381900083ba64
    sa-east-1:
      AMIID: ami-05313c3a9e9148109

Resources:
  CloudMap:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: Service Map for Docker Compose project orthanconaws
      Name: orthanconaws.local
      Vpc: !Ref 'ParameterVPCId'
  Cluster:
    Type: AWS::ECS::Cluster
    Condition: CreateCluster
    Properties:
      ClusterName: orthanconaws
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
  LogGroup:
    Properties:
      LogGroupName: /docker-compose/orthanconaws
    Type: AWS::Logs::LogGroup

  DataBaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup for RDS instances
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
  OrthancRDSNetwork:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OrthancOnAWS RDS Security Group
      GroupName: OrthancRDSNetwork
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref 'OrthancServerNetwork'
          Description: postgres:5432/tcp
          FromPort: 5432
          IpProtocol: TCP
          ToPort: 5432
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
        - Key: com.docker.compose.network
          Value: rds
      VpcId: !Ref 'ParameterVPCId'
  PostgreSQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: orthanc-instance
      DBName: orthanc
      DBInstanceClass: !Ref RDSDBInstanceClass
      StorageType: !Ref RDSDBStorageType
      AllocatedStorage: !Ref RDSDBAllocatedStorage
      Engine: postgres
      EngineVersion: 11
      MasterUsername: postgres
      MasterUserPassword: pgpassword
      PubliclyAccessible: True
      Tags:
        - Key: com.docker.compose.project
          Value: "RDS PostgreSQL for Orthanc"
      VPCSecurityGroups: 
        - !Ref OrthancRDSNetwork
      DBSubnetGroupName: !Ref DataBaseSubnetGroup
  OrthancServerNetwork:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OrthancOnAWS default Security Group
      GroupName: OrthancServerNetwork
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          Description: orthanc:4242/tcp
          FromPort: 4242
          IpProtocol: TCP
          ToPort: 4242
        - CidrIp: '0.0.0.0/0'
          Description: nginx:443/tcp
          FromPort: 443
          IpProtocol: TCP
          ToPort: 443
        - CidrIp: '0.0.0.0/0'
          Description: ssh:22/tcp
          FromPort: 22
          IpProtocol: TCP
          ToPort: 22
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
        - Key: com.docker.compose.network
          Value: default
      VpcId: !Ref 'ParameterVPCId'
  OrthancServerNetworkIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow communication within network default
      GroupId: !Ref 'OrthancServerNetwork'
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref 'OrthancServerNetwork'
  orthanconawsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition: CreateLoadBalancer
    Properties:
      Name: orthanconawsLoadBalancer
      Scheme: internet-facing
      Subnets:
        - !Ref 'PublicSubnet1Id'
        - !Ref 'PublicSubnet2Id'
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
      Type: network

  OrthancService:
    Type: AWS::ECS::Service
    DependsOn:
      - OrthancTCP4242Listener
      - OrthancTCP443Listener
    Properties:
      Cluster: !If
        - CreateCluster
        - !Ref 'Cluster'
        - !Ref 'ParameterClusterName'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 2
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: orthanc
          ContainerPort: 4242
          TargetGroupArn: !Ref 'OrthancTCP4242TargetGroup'
        - ContainerName: orthanc
          ContainerPort: 443
          TargetGroupArn: !Ref 'OrthancTCP443TargetGroup'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref 'OrthancServerNetwork'
          Subnets:
            - !Ref 'PublicSubnet1Id'
            - !Ref 'PublicSubnet2Id'
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      ServiceRegistries:
        - RegistryArn: !GetAtt 'OrthancServiceDiscoveryEntry.Arn'
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
        - Key: com.docker.compose.service
          Value: orthanc
      TaskDefinition: !Ref 'OrthancTaskDefinition'
  OrthancServiceDiscoveryEntry:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: '"orthanc" service discovery entry in Cloud Map'
      DnsConfig:
        DnsRecords:
          - TTL: 60
            Type: A
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: orthanc
      NamespaceId: !Ref 'CloudMap'
  OrthancTCP4242Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref 'OrthancTCP4242TargetGroup'
          Type: forward
      LoadBalancerArn: !If
        - CreateLoadBalancer
        - !Ref 'orthanconawsLoadBalancer'
        - !Ref 'ParameterLoadBalancerARN'
      Port: 4242
      Protocol: TCP
  OrthancTCP4242TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 4242
      Protocol: TCP
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
      TargetType: ip
      VpcId: !Ref 'ParameterVPCId'
  OrthancTCP443Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref 'OrthancTCP443TargetGroup'
          Type: forward
      LoadBalancerArn: !If
        - CreateLoadBalancer
        - !Ref 'orthanconawsLoadBalancer'
        - !Ref 'ParameterLoadBalancerARN'
      Port: 443
      Protocol: TCP
  OrthancTCP443TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 443
      Protocol: TCP
      Tags:
        - Key: com.docker.compose.project
          Value: orthanconaws
      TargetType: ip
      VpcId: !Ref 'ParameterVPCId'
  OrthancTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - PostgreSQLRDSInstance
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: ORTHANC__POSTGRESQL__HOST
              Value: !GetAtt 'PostgreSQLRDSInstance.Endpoint.Address'
            - Name: LOCALDOMAIN
              Value: !Join
                - ''
                - - !Ref 'AWS::Region'
                  - .compute.internal
                  - ' orthanconaws.local'
            - Name: ORTHANC__REGISTERED_USERS
              Value: "{\"demo\": \"demo\"}\n"
            - Name: ORTHANC_JSON
              Value: |
                {
                  "Name" : "Orthanc in Docker",
                  "RemoteAccessAllowed" : true,
                  "PostgreSQL" : {
                    "EnableIndex" : true,
                    "EnableStorage" : true,
                    "Host" : "172.17.0.38",
                    "Port" : 5432,
                    "Database" : "orthanc",
                    "Username" : "postgres",
                    "Password" : "pgpassword"
                  },
                  "DicomWeb": {
                    "Enable": true
                  }
                }
          Essential: true
          Image: !Ref 'ConainerImageUrl'
          LinuxParameters: {}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'LogGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: orthanconaws
          Name: orthanc
          PortMappings:
            - ContainerPort: 4242
              HostPort: 4242
              Protocol: tcp
            - ContainerPort: 8042
              HostPort: 8042
              Protocol: tcp
            - ContainerPort: 443
              HostPort: 443
              Protocol: tcp
      Cpu: '2048'
      ExecutionRoleArn: !Ref 'OrthancTaskExecutionRole'
      Family: orthanconaws-orthanc
      Memory: '4096'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
  OrthancTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref 'PublicSubnet1Id'
        - !Ref 'PublicSubnet2Id'
      LaunchConfigurationName: !Ref 'ContainerInstances'
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'
  ContainerInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID]
      SecurityGroups:
            - !Ref 'OrthancServerNetwork'
      InstanceType: !Ref 'InstanceType'
      IamInstanceProfile: !Ref 'EC2InstanceProfile'
      KeyName: !Ref 'KeyName'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${Cluster} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ECSAutoScalingGroup --region ${AWS::Region}
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'EC2Role']


Outputs:
  OrthancNginxEndpoint:
    Description: The URL for Nginx reverse proxy of Orthanc web server endpoint
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt orthanconawsLoadBalancer.DNSName

      
